/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProgramePack.UI;

/**
 *
 * @author crane
 */
import javax.swing.*;
import java.awt.*;
import ProgramePack.Project.Booking;

public class BookingPanel extends JPanel {

    private Booking booking;

    private JLabel idLabel;
    private JLabel typeLabel;
    private JLabel customerLabel;
    private JLabel roomLabel;
    private JLabel fareLabel;
    private JLabel checkInLabel;
    private JLabel checkOutLabel;

    public BookingPanel(Booking booking) {
        this.booking = booking;
        setLayout(new GridLayout(7, 2));

        idLabel = new JLabel("Booking ID:");
        add(idLabel);
        JLabel idValueLabel = new JLabel(Integer.toString(booking.getBooking_id()));
        add(idValueLabel);

        typeLabel = new JLabel("Booking Type:");
        add(typeLabel);
        JLabel typeValueLabel = new JLabel(booking.getBookingType());
        add(typeValueLabel);

        customerLabel = new JLabel("Customer:");
        add(customerLabel);
        JLabel customerValueLabel = new JLabel(booking.getCustomer().getName());
        add(customerValueLabel);

        roomLabel = new JLabel("Room No(s):");
        add(roomLabel);
        JLabel roomValueLabel = new JLabel(booking.getRooms().toString());
        add(roomValueLabel);

        fareLabel = new JLabel("Total Fare:");
        add(fareLabel);
        JLabel fareValueLabel = new JLabel(Integer.toString(booking.getRoomsFare()));
        add(fareValueLabel);

        checkInLabel = new JLabel("Check-In Time:");
        add(checkInLabel);
        JLabel checkInValueLabel = new JLabel(Long.toString(booking.getCheckInDateTime()));
        add(checkInValueLabel);

        checkOutLabel = new JLabel("Check-Out Time:");
        add(checkOutLabel);
        JLabel checkOutValueLabel = new JLabel(Long.toString(booking.getCheckOutDateTime()));
        add(checkOutValueLabel);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
